{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}

spec:
  ingressClassName: {{ .Values.ingress.className }}
  # TODO: Add TLS configuration
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | default "" }}
      http:
        paths:
          {{- range .paths }}
            - path: {{ .path }}
              pathType: {{ .pathType }}
              backend:
                service:
                  name: {{ .serviceName | default (include "helm.fullname" $) }}
                  port:
                    number: {{ .servicePort | default $.Values.service.port }}
          {{- end }}
    {{- end }}
    
{{- end }}
  