# Pre-install/upgrade hook to run Prisma migrations
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-migrate
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prisma-migrate
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["npx", "prisma", "migrate", "deploy"]
          
          # Environment variables
          {{- if .Values.env }}
          env:
            {{- .Values.env | toYaml | nindent 12 }}
          {{- end }}
